heat_template_version: 2015-04-30

parameters:

  overcloud_flavor:
    type: string
    default: overcloud
    description: Recommended to be at least 1 vcpu, 4 GB RAM, 50 GB disk

  overcloud_image:
    type: string
    default: empty
    description: The base image to use for overcloud instances

  key_name:
    type: string
    default: default
    description: Nova keypair to inject into the undercloud and overcloud servers

  overcloud_node_count:
    type: number
    default: 2
    description: Number of overcloud nodes to deploy

  private_net:
    type: string
    default: private
    description: Name of a private network which can have floating ips associated with it

  public_net:
    type: string
    description: Name of the overcloud external network
    default: public

  overcloud_prefix:
    type: string
    default: overcloud
    description: Prefix for the name of the overcloud instances

  undercloud_name:
    type: string
    default: undercloud
    description: Name of the undercloud instance

  undercloud_flavor:
    type: string
    default: m1.large
    description: Nova flavor to use for the undercloud instance

  undercloud_image:
    type: string
    default: CentOS-7-x86_64-GenericCloud-1503
    description: Image to boot as the undercloud instance

  undercloud_user_data:
    type: string
    default: ""
    description: Userdata to inject into the undercloud instance

  undercloud_user_data_format:
    type: string
    default: RAW
    description: Format of undercloud userdata

resources:

  public_network:
    type: OS::TraaS::PublicNetwork
    properties:
      public_net: {get_param: public_net}

  private_network:
    type: OS::TraaS::PrivateNetwork
    properties:
      private_net: {get_param: private_net}

  undercloud:
    depends_on: [public_network]
    type: OS::TraaS::Undercloud
    properties:
      undercloud_flavor: {get_param: undercloud_flavor}
      undercloud_image: {get_param: undercloud_image}
      key_name: {get_param: key_name}
      undercloud_name: {get_param: undercloud_name}
      undercloud_user_data_format: {get_param: undercloud_user_data_format}
      undercloud_user_data: {get_param: undercloud_user_data}
      private_net: {get_attr: [private_network, private_net]}
      public_net: {get_attr: [public_network, public_net]}

  overcloud_nodes:
    type: OS::TraaS::OvercloudNodes
    depends_on: [public_network]
    properties:
      overcloud_flavor: {get_param: overcloud_flavor}
      overcloud_image: {get_param: overcloud_image}
      key_name: {get_param: key_name}
      node_count: {get_param: overcloud_node_count}
      public_net: {get_attr: [public_network, public_net]}
      private_net: {get_attr: [private_network, private_net]}
      overcloud_prefix: {get_param: overcloud_prefix}

outputs:
